#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: ip-172-31-35-144.us-east-2.compute.internal




rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - ip-172-31-35-144.us-east-2.compute.internal:9090
      - localhost:9100
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

